CHARACTER_MAPPINGS = {
    "one_piece": {
        "monkey_d_luffy": ["monkey d luffy", "monkey_d_luffy", "luffy", "strawhat"],
        "roronoa_zoro": ["roronoa zoro", "roronoa_zoro", "zoro"],
        "nami": ["nami", "nami_(one_piece)"],
        "vinsmoke_sanji": ["vinsmoke sanji", "vinsmoke_sanji", "sanji", "black leg"],
        "nico_robin": ["nico robin", "nico_robin", "robin", "robin_(alabasta)", "robin_(cosplay)"],
        "uta": ["uta", "uta_(one_piece)"],
        "rebecca": ["rebecca", "rebecca_(one_piece)"],
        "carrot": ["carrot", "carrot_(one_piece)"],
        "jewelry_bonney": ["jewelry bonney", "jewelry_bonney", "bonney"],
        "baby_5": ["baby 5", "baby_5", "baby five", "baby_five"],
        "boa_hancock": ["boa hancock", "boa_hancock", "hancock"],
        "nefertari_vivi": ["nefertari vivi", "nefertari_vivi", "vivi"],
        "vinsmoke_reiju": ["vinsmoke reiju", "vinsmoke_reiju", "reiju"],
        "charlotte_linlin": ["big mom", "big_mom", "charlotte_linlin", "charlotte linlin", "linlin"],
        "shimotsuki_kuina": ["shimotsuki kuina", "shimotsuki_kuina", "kuina"],
        "charlotte_smoothie": ["charlotte_smoothie", "charlotte smoothie", "smoothie"],
        "shirahoshi": ["shirahoshi", "princess shirahoshi", "princess_shirahoshi"],
        "kouzuki_hiyori": ["hiyori", "kouzuki hiyori", "kouzuki_hiyori"],
        "catarina_devon": ["devon", "catarina devon", "catarina_devon"],
        "perona": ["perona", "'ghost princess' perona", "ghost princess perona", "'ghost_princess'_perona", "ghost_princess_perona"],
        "charlotte_flampe": ["charlotte_flampe", "charlotte flampe", "flampe"],
        "kouzuki_toki": ["kouzuki toki", "kouzuki_toki", "toki"],
        "alvida": ["alvida", "alvida_(one_piece)"],
        "kikunojo": ["kikunojo", "kikunojo_(one_piece)", "kiku"],
        "vegapunk_lilith": ["vegapunk lilith", "vegapunk_lilith", "lilith"],
        "kaya": ["kaya", "kaya_(one_piece)"],
        "monet": ["monet", "monet_(one_piece)"],
        "wanda": ["wanda", "wanda_(one_piece)"],
        "nico_olvia": ["nico olvia", "nico_olvia", "olvia"],
        "nojiko": ["nojiko"],
        "charlotte_pudding": ["charlotte pudding", "charlotte_pudding", "pudding"],
        "vegapunk_atlas": ["vegapunk atlas", "vegapunk_atlas", "atlas"],
        "vegapunk_york": ["vegapunk york", "vegapunk_york", "york"],
        "stussy": ["stussy", "stussy_(one_piece)"],
        "tashigi": ["tashigi"],
        "hina": ["hina", "hina_(one_piece)"],
        "isuka": ["isuka", "isuka_(one_piece)"]
    },

    "dota_2": {
        "lina": ["lina", "lina inverse"],
        "crystal_maiden": ["crystal maiden", "crystal_maiden", "rylai"],
        "invoker": ["invoker", "kael"],
        "windrunner": ["windranger", "windrunner", "lyralei", "windranger_(dota)"],
        "marci": ["marci", "marci_(dota)"],
        "dark_willow": ["dark willow", "dark_willow"],
        "mirana": ["mirana", "mirana_(dota)"],
        "broodmother": ["broodmother", "broodmother_(dota)"],
        "dawnbreaker": ["dawnbreaker", "dawnbreaker_(dota)", "dawnbreaker_(dota_2)"],
        "death_prophet": ["death prophet", "death_prophet_(dota)"],
        "enchantress": ["enchantress", "enchantress_(dota)", "enchantress_(dota_2)"],
        "legion_commander": ["legion commander", "legion_commander_(dota)"],
        "luna": ["luna", "luna_(dota)"],
        "naga_siren": ["naga siren", "naga_siren_(dota)"],
        "phantom_assassin": ["phantom assassin", "phantom_assassin_(dota)"],
        "queen_of_pain": ["queen of pain", "queen_of_pain_(dota)"],
        "snapfire": ["snapfire"],
        "spectre": ["spectre", "spectre_(dota)"],
        "templar_assassin": ["templar assassin", "templar_assassin_(dota)"],
        "vengeful_spirit": ["vengeful spirit", "vengeful_spirit_(dota_2)"]
    },

    "naruto": {
        "tsunade_senju": ["tsunade senju", "tsunade", "lady tsunade", "princess tsunade"],
        "sakura_haruno": ["sakura haruno", "sakura_haruno"],
        "hinata_hyuga": ["hinata hyuga", "hinata_hyuga"],
        "tenten": ["tenten"],
        "temari": ["temari"],
        "kushina_uzumaki": ["kushina uzumaki", "kushina_uzumaki"],
        "sarada_uchiha": ["sarada uchiha", "sarada_uchiha"],
        "himawari_uzumaki": ["himawari uzumaki", "himawari_uzumaki"],
        "ino_yamanaka": ["ino yamanaka", "ino_yamanaka"],
        "kurenai_yuhi": ["kurenai yuhi", "kurenai_yuhi"],
        "anko_mitarashi": ["anko mitarashi", "anko_mitarashi"],
        "shizune": ["shizune"],
        "karin_uzumaki": ["karin uzumaki", "karin_uzumaki"],
        "konan": ["konan"],
        "mei_terumi": ["mei terumi", "mei_terumi"],
        "samui": ["samui"],
        "karui": ["karui"],
        "mabui": ["mabui"],
        "yugao_uzuki": ["yugao uzuki", "yugao_uzuki"],
        "tsume_inuzuka": ["tsume inuzuka", "tsume_inuzuka"],
        "hana_inuzuka": ["hana inuzuka", "hana_inuzuka"],
        "natsu_hyuga": ["natsu hyuga", "natsu_hyuga"],
        "yakumo_kurama": ["yakumo kurama", "yakumo_kurama"],
        "tsunami": ["tsunami"],
        "ayame": ["ayame"],
        "yugito_nii": ["yugito nii", "yugito_nii"],
        "fuu": ["fuu"],
        "hokuto": ["hokuto"],
        "hanabi_hyuga": ["hanabi hyuga", "hanabi_hyuga"],
        "moegi": ["moegi"],
        "sumire_kakei": ["sumire kakei", "sumire_kakei"],
        "chocho_akimichi": ["chocho akimichi", "chocho_akimichi"],
        "mirai_sarutobi": ["mirai sarutobi", "mirai_sarutobi"],
        "wasabi_izuno": ["wasabi izuno", "wasabi_izuno"],
        "namida_suzumeno": ["namida suzumeno", "namida_suzumeno"]
    },

    "fairy_tail": {
         "lucy_heartfilia": ["lucy heartfilia", "lucy_heartfilia"],
        "erza_scarlet": ["erza scarlet", "erza_scarlet", "titania"],
        "wendy_marvell": ["wendy marvell", "wendy_marvell"],
        "juvia_lockser": ["juvia lockser", "juvia_lockser"],
        "levy_mcgarden": ["levy mcgarden", "levy_mcgarden"],
        "mirajane_strauss": ["mirajane strauss", "mirajane_strauss"],
        "lisanna_strauss": ["lisanna strauss", "lisanna_strauss"],
        "cana_alberona": ["cana alberona", "cana_alberona"],
        "evergreen": ["evergreen"],
        "bisca_connell": ["bisca connell", "bisca_connell"],
        "laki_olietta": ["laki olietta", "laki_olietta"],
        "kinana": ["kinana"],
        "mavis_vermillion": ["mavis vermillion", "mavis_vermillion"],
        "meredy": ["meredy"],
        "ultear_milkovich": ["ultear milkovich", "ultear_milkovich"],
        "yukino_agria": ["yukino agria", "yukino_agria"],
        "minerva_orlando": ["minerva orlando", "minerva_orlando"],
        "kagura_mikazuchi": ["kagura mikazuchi", "kagura_mikazuchi"],
        "milliana": ["milliana"],
        "flare_corona": ["flare corona", "flare_corona"],
        "jenny_realight": ["jenny realight", "jenny_realight"],
        "sherry_blendy": ["sherry blendy", "sherry_blendy"],
        "chelia_blendy": ["chelia blendy", "chelia_blendy"],
        "sorano_agria": ["sorano agria", "sorano_agria", "angel"],
        "brandish_mu": ["brandish μ", "brandish mu"],
        "dimaria_yesta": ["dimaria yesta", "dimaria_yesta"],
        "irene_belserion": ["irene belserion", "irene_belserion"],
        "hisui_fiore": ["hisui e fiore", "hisui_e_fiore"]
    },

    "dragon_ball": {
        "bulma_briefs": ["bulma briefs", "bulma_briefs"],
        "chi_chi": ["chi chi", "chi_chi"],
        "videl_satan": ["videl", "videl_satan"],
        "pan": ["pan"],
        "android_18": ["android 18", "c-18", "lazuli"],
        "bulla_briefs": ["bulla", "bra"],
        "launch": ["launch", "lunch"],
        "marron": ["marron"],
        "mai": ["mai"],
        "ranfan": ["ranfan"],
        "vados": ["vados"],
        "caulifla": ["caulifla"],
        "kale": ["kale"],
        "ribrianne": ["ribrianne", "brianne de chateau"],
        "oceanus_shenron": ["oceanus shenron", "princess oto"],
        "gine": ["gine"],
        "fasha": ["fasha", "selypa"],
        "zangya": ["zangya"],
        "towa": ["towa"],
        "chronoa": ["supreme kai of time", "chronoa"],
        "arale_norimaki": ["arale norimaki", "arale_norimaki"]
    },

    "attack_on_titan": {
        "mikasa_ackerman": ["mikasa ackerman", "mikasa_ackerman"],
        "annie_leonhart": ["annie leonhart", "annie_leonhart"],
        "historia_reiss": ["historia reiss", "historia_reiss", "christa"],
        "sasha_braus": ["sasha braus", "sasha_braus"],
        "hange_zoe": ["hange zoe", "hanji"],
        "ymir": ["ymir", "freckled ymir"],
        "pieck_finger": ["pieck finger", "pieck_finger"],
        "gabi_braun": ["gabi braun", "gabi_braun"],
        "frieda_reiss": ["frieda reiss", "frieda_reiss"],
        "carla_yeager": ["carla yeager", "carla_yeager"],
        "dina_fritz": ["dina fritz", "dina_fritz"],
        "petra_ral": ["petra ral", "petra_ral"],
        "rico_brzenska": ["rico brzenska", "rico_brzenska"],
        "yelena": ["yelena"],
        "kiyomi_azumabito": ["kiyomi azumabito", "kiyomi_azumabito"],
        "louise": ["louise"],
        "nifa": ["nifa"],
        "lynne": ["lynne"],
        "ilse_langnar": ["ilse langnar", "ilse_langnar"],
        "nanaba": ["nanaba"]
    },

    "demon_slayer": {
        "nezuko_kamado": ["nezuko kamado", "nezuko_kamado"],
        "kanao_tsuyuri": ["kanao tsuyuri", "kanao_tsuyuri"],
        "shinobu_kocho": ["shinobu kocho", "shinobu_kocho"],
        "kanae_kocho": ["kanae kocho", "kanae_kocho"],
        "mitsuri_kanroji": ["mitsuri kanroji", "mitsuri_kanroji"],
        "daki": ["daki", "ume"],
        "tamayo": ["tamayo"],
        "makio": ["makio"],
        "suma": ["suma"],
        "hinatsuru": ["hinatsuru"],
        "aoi_kanzaki": ["aoi kanzaki", "aoi_kanzaki"],
        "kiyo_terauchi": ["kiyo terauchi", "kiyo_terauchi"],
        "sumi_nakahara": ["sumi nakahara", "sumi_nakahara"],
        "naho_takada": ["naho takada", "naho_takada"],
        "goto": ["goto", "goto_san"],
        "amane": ["amane"],
        "mukago": ["mukago"],
        "ruka": ["ruka"],
        "hinaki_ubuyashiki": ["hinaki ubuyashiki", "hinaki_ubuyashiki"],
        "nichika_ubuyashiki": ["nichika ubuyashiki", "nichika_ubuyashiki"],
        "kuina_ubuyashiki": ["kuina ubuyashiki", "kuina_ubuyashiki"]
    },

    "jujutsu_kaisen": {
        "nobara_kugisaki": ["nobara kugisaki", "nobara_kugisaki"],
        "maki_zenin": ["maki zenin", "maki_zenin"],
        "mei_mei": ["mei mei", "mei_mei"],
        "kasumi_miwa": ["kasumi miwa", "kasumi_miwa"],
        "momo_nishimiya": ["momo nishimiya", "momo_nishimiya"],
        "mai_zenin": ["mai zenin", "mai_zenin"],
        "yuki_tsukumo": ["yuki tsukumo", "yuki_tsukumo"],
        "rika_orimoto": ["rika orimoto", "rika_orimoto"],
        "utahime_iori": ["utahime iori", "utahime_iori"],
        "tsumiki_fushiguro": ["tsumiki fushiguro", "tsumiki_fushiguro"],
        "manami_suda": ["manami suda", "manami_suda"],
        "saori_rokujo": ["saori rokujo", "saori_rokujo"],
        "shoko_ieiri": ["shoko ieiri", "shoko_ieiri"],
        "mimiko_hasaba": ["mimiko hasaba", "mimiko_hasaba"],
        "nanako_hasaba": ["nanako hasaba", "nanako_hasaba"]
    },

    "cowboy_bebop": {
        "faye_valentine": ["faye valentine", "faye_valentine"],
        "edward_wong": ["edward wong", "radical ed", "edward"],
        "julia": ["julia"],
        "meifa_puzi": ["meifa puzi", "meifa_puzi"],
        "judy": ["judy"],
        "anastasia": ["anastasia", "annie"],
        "alisa": ["alisa"],
        "victoria_terraforming": ["v.t.", "victoria terraforming"],
        "stella_bonnaro": ["stella bonnaro", "stella_bonnaro"],
        "coffee": ["coffee"],
        "katrina_solensan": ["katrina solensan", "katrina_solensan"]
    },

    "spy_x_family": {
        "yor_forger": ["yor forger", "yor_forger", "thorn princess"],
        "anya_forger": ["anya forger", "anya_forger"],
        "sylvia_sherwood": ["sylvia sherwood", "sylvia_sherwood"],
        "fiona_frost": ["fiona frost", "fiona_frost"],
        "becky_blackbell": ["becky blackbell", "becky_blackbell"],
        "sharon": ["sharon", "shop_keeper"],
        "melinda_desmond": ["melinda desmond", "melinda_desmond"],
        "camilla": ["camilla", "shopkeeper_sister"],
        "karen_gloomy": ["karen gloomy", "karen_gloomy"],
        "dominic": ["dominic", "handler"],
        "martha": ["martha", "landlady"]
    },

    "one_punch_man": {
        "fubuki": ["fubuki", "blizzard", "hellish blizzard"],
        "tatsumaki": ["tatsumaki", "tornado", "tornado of terror"],
        "psykos": ["psykos"],
        "suiko": ["suiko"],
        "lin_lin": ["lin lin"],
        "lily": ["lily of the three section staff", "lily"],
        "do_s": ["do-s", "monster princess"],
        "mosquito_girl": ["mosquito girl"],
        "captain_mizuki": ["captain mizuki", "mizuki"],
        "shadow_ring": ["shadow ring"],
        "zenko": ["zenko", "metal bat's sister"],
        "madame_shibabawa": ["madame shibabawa"],
        "goddess_glasses": ["goddess glasses"],
        "swim": ["swim"],
        "pai": ["pai"]
    },

    "league_of_legends": {
        "ahri": ["ahri"],
        "lux": ["lux", "luxanna crownguard"],
        "jinx": ["jinx"],
        "vi": ["vi"],
        "caitlyn": ["caitlyn"],
        "leona": ["leona"],
        "diana": ["diana"],
        "ashe": ["ashe"],
        "katarina": ["katarina"],
        "miss_fortune": ["miss fortune", "sarah fortune"],
        "akali": ["akali"],
        "anivia": ["anivia"],
        "annie": ["annie"],
        "bel_veth": ["bel'veth", "belveth"],
        "briar": ["briar"],
        "cassiopeia": ["cassiopeia"],
        "elise": ["elise"],
        "evelynn": ["evelynn"],
        "fiora": ["fiora"],
        "gwen": ["gwen"],
        "illaoi": ["illaoi"],
        "irelia": ["irelia"],
        "janna": ["janna"],
        "kai_sa": ["kai'sa", "kaisa"],
        "kalista": ["kalista"],
        "karma": ["karma"],
        "kindred": ["kindred"],
        "leblanc": ["leblanc"],
        "lillia": ["lillia"],
        "lissandra": ["lissandra"],
        "morgana": ["morgana"],
        "nami": ["nami"],
        "neeko": ["neeko"],
        "nidalee": ["nidalee"],
        "nilah": ["nilah"],
        "orianna": ["orianna"],
        "poppy": ["poppy"],
        "qiyana": ["qiyana"],
        "rell": ["rell"],
        "riven": ["riven"],
        "samira": ["samira"],
        "senna": ["senna"],
        "seraphine": ["seraphine"],
        "sejuani": ["sejuani"],
        "senna": ["senna"],
        "shyvana": ["shyvana"],
        "sivir": ["sivir"],
        "sona": ["sona"],
        "soraka": ["soraka"],
        "syndra": ["syndra"],
        "taliyah": ["taliyah"],
        "tristana": ["tristana"],
        "vayne": ["vayne"],
        "vex": ["vex"],
        "xayah": ["xayah"],
        "yuumi": ["yuumi"],
        "zeri": ["zeri"],
        "zoe": ["zoe"],
        "zyra": ["zyra"]
    },

    "hunter_x_hunter": {
        "biscuit_krueger": ["biscuit krueger", "bisky"],
        "palm_siberia": ["palm siberia"],
        "machi": ["machi"],
        "shizuku": ["shizuku"],
        "canary": ["canary"],
        "neferpitou": ["neferpitou", "pitou"],
        "komugi": ["komugi"],
        "pakunoda": ["pakunoda"],
        "melody": ["melody", "senritsu"],
        "zazan": ["zazan"],
        "eliza": ["eliza"],
        "amane": ["amane"],
        "tsubone": ["tsubone"],
        "kalluto_zoldyck": ["kalluto zoldyck", "kalluto_zoldyck"],
        "kikyo_zoldyck": ["kikyo zoldyck", "kikyo_zoldyck"],
        "alluka_zoldyck": ["alluka zoldyck", "alluka_zoldyck"],
        "cheadle_yorkshire": ["cheadle yorkshire", "cheadle_yorkshire"],
        "menchi": ["menchi"],
        "ponzu": ["ponzu"]
    },

    "fullmetal_alchemist": {
        "winry_rockbell": ["winry rockbell", "winry_rockbell"],
        "riza_hawkeye": ["riza hawkeye", "riza_hawkeye"],
        "olivier_armstrong": ["olivier armstrong", "olivier_armstrong"],
        "izumi_curtis": ["izumi curtis", "izumi_curtis"],
        "mei_chang": ["mei chang", "mei_chang"],
        "maria_ross": ["maria ross", "maria_ross"],
        "gracia_hughes": ["gracia hughes", "gracia_hughes"],
        "elicia_hughes": ["elicia hughes", "elicia_hughes"],
        "lan_fan": ["lan fan", "lan_fan"],
        "paninya": ["paninya"],
        "sheska": ["sheska", "sciezka"],
        "rose_thomas": ["rose thomas", "rose_thomas"],
        "catherine_armstrong": ["catherine elle armstrong", "catherine_armstrong"],
        "martel": ["martel"],
        "trisha_elric": ["trisha elric", "trisha_elric"],
        "pinako_rockbell": ["pinako rockbell", "pinako_rockbell"],
        "lust": ["lust"],
        "dante": ["dante"],
        "clara": ["clara", "psiren"]
    },

    "my_hero_academia": {
        "ochaco_uraraka": ["ochaco uraraka", "ochaco_uraraka"],
        "tsuyu_asui": ["tsuyu asui", "tsuyu_asui", "froppy"],
        "momo_yaoyorozu": ["momo yaoyorozu", "momo_yaoyorozu"],
        "kyoka_jirou": ["kyoka jirou", "kyoka_jirou"],
        "toru_hagakure": ["toru hagakure", "toru_hagakure"],
        "mina_ashido": ["mina ashido", "mina_ashido", "pinky"],
        "yu_takeyama": ["mount lady", "yu takeyama"],
        "nemuri_kayama": ["midnight", "nemuri kayama"],
        "rumi_usagiyama": ["mirko", "rumi usagiyama"],
        "ryuko_tatsuma": ["ryuku", "ryuko tatsuma"],
        "nejire_hado": ["nejire hado", "nejire_hado"],
        "shino_sosaki": ["mandalay", "shino sosaki"],
        "ryuko_tsuchikawa": ["pixie-bob", "ryuko tsuchikawa"],
        "tomoko_shiretoko": ["ragdoll", "tomoko shiretoko"],
        "itsuka_kendo": ["itsuka kendo", "itsuka_kendo"],
        "pony_tsunotori": ["pony tsunotori", "pony_tsunotori"],
        "kinoko_komori": ["kinoko komori", "kinoko_komori"],
        "yui_kodai": ["yui kodai", "yui_kodai"],
        "reiko_yanagi": ["reiko yanagi", "reiko_yanagi"],
        "setsuna_tokage": ["setsuna tokage", "setsuna_tokage"],
        "melissa_shield": ["melissa shield", "melissa_shield"],
        "inko_midoriya": ["inko midoriya", "inko_midoriya"],
        "fuyumi_todoroki": ["fuyumi todoroki", "fuyumi_todoroki"],
        "eri": ["eri"],
        "nana_shimura": ["nana shimura", "nana_shimura"],
        "himiko_toga": ["himiko toga", "himiko_toga"]
    },

    "jojos_bizarre_adventure": {
        "jolyne_cujoh": ["jolyne cujoh", "jolyne_cujoh"],
        "lisa_lisa": ["lisa lisa", "lisa_lisa"],
        "erina_pendleton": ["erina pendleton", "erina_pendleton"],
        "trish_una": ["trish una", "trish_una"],
        "suzi_q": ["suzi q", "suzi_q"],
        "holly_kujo": ["holly kujo", "holly_kujo", "seiko"],
        "yukako_yamagishi": ["yukako yamagishi", "yukako_yamagishi"],
        "reimi_sugimoto": ["reimi sugimoto", "reimi_sugimoto"],
        "hot_pants": ["hot pants", "hot_pants"],
        "lucy_steel": ["lucy steel", "lucy_steel"],
        "yasuho_hirose": ["yasuho hirose", "yasuho_hirose"],
        "hermes_costello": ["hermes costello", "hermes_costello"],
        "foo_fighters": ["foo fighters", "f.f.", "ff"],
        "ermes_costello": ["ermes costello", "ermes_costello"],
        "gwess": ["gwess"],
        "mariah": ["mariah"],
        "midler": ["midler", "rose"],
        "anne": ["anne"],
        "tomoko_higashikata": ["tomoko higashikata", "tomoko_higashikata"]
    },

    "pokemon": {
        "misty_waterflower": ["misty", "kasumi"],
        "may_maple": ["may", "haruka"],
        "dawn_berlitz": ["dawn", "hikari"],
        "serena": ["serena"],
        "iris": ["iris"],
        "lillie": ["lillie"],
        "cynthia": ["cynthia", "shirona"],
        "diantha": ["diantha"],
        "lusamine": ["lusamine"],
        "sabrina": ["sabrina"],
        "erika": ["erika"],
        "whitney": ["whitney"],
        "jasmine": ["jasmine"],
        "clair": ["clair"],
        "flannery": ["flannery"],
        "winona": ["winona"],
        "roxanne": ["roxanne"],
        "gardenia": ["gardenia"],
        "candice": ["candice"],
        "fantina": ["fantina"],
        "elesa": ["elesa"],
        "skyla": ["skyla"],
        "korrina": ["korrina"],
        "valerie": ["valerie"],
        "olympia": ["olympia"],
        "mallow": ["mallow"],
        "lana": ["lana"],
        "nessa": ["nessa"],
        "marnie": ["marnie"],
        "sonia": ["sonia"],
        "professor_juniper": ["professor juniper", "professor_juniper"],
        "nurse_joy": ["nurse joy", "joy"],
        "officer_jenny": ["officer jenny", "jenny"],
        "jessie": ["jessie", "musashi"],
        "bonnie": ["bonnie", "eureka"],
        "rosa": ["rosa"]
    },

    "hatsune_miku": {
        "hatsune_miku": ["hatsune miku", "hatsune_miku", "miku", "initial miku", "initial_miku", "miku_(vocaloid)",
                         "miku_(project_diva)"],
        "meiko": ["meiko", "meiko_(vocaloid)", "meiko_(project_diva)"],
        "kagamine_rin": ["kagamine rin", "kagamine_rin", "rin", "rin_(vocaloid)", "rin_(project_diva)"],
        "megurine_luka": ["megurine luka", "megurine_luka", "luka", "luka_(vocaloid)", "luka_(project_diva)"],
        "megpoid_gumi": ["gumi", "megpoid", "gumi_(vocaloid)", "gumi_(project_diva)"],
        "kasane_teto": ["kasane teto", "kasane_teto", "teto", "teto_(utau)"],
        "akita_neru": ["akita neru", "akita_neru", "neru", "neru_(derivative)"],
        "yowane_haku": ["yowane haku", "yowane_haku", "haku", "haku_(derivative)"],
        "otomachi_una": ["otomachi una", "otomachi_una", "una", "una_(vocaloid)"],
        "ia": ["ia", "ia_(vocaloid)", "aria on the planetes"],
        "cul": ["cul", "cul_(vocaloid)"],
        "lily": ["lily", "lily_(vocaloid)"],
        "sf_a2_miki": ["sf-a2 miki", "sf_a2_miki", "miki", "miki_(vocaloid)"],
        "yuzuki_yukari": ["yuzuki yukari", "yuzuki_yukari", "yukari", "yukari_(vocaloid)"]
    },

    "konosuba": {
        "aqua": ["aqua", "aqua_(konosuba)", "goddess_aqua", "useless_goddess"],
        "megumin": ["megumin", "megumin_(konosuba)", "explosion_girl", "crimson_demon_megumin"],
        "lalatina_dustiness": ["darkness", "darkness_(konosuba)", "dustiness_ford_lalatina", "lalatina",
                               "crusader_darkness"],
        "wiz": ["wiz", "wiz_(konosuba)", "lich_wiz"],
        "yunyun": ["yunyun", "yun yun", "yun_yun", "yunyun_(konosuba)"],
        "chris": ["chris", "chris_(konosuba)", "eris", "eris_(konosuba)", "assistant_goddess"],
        "luna": ["luna", "luna_(konosuba)", "guild_receptionist"],
        "sena": ["sena", "sena_(konosuba)"],
        "wolbach": ["wolbach", "goddess_wolbach", "wolbach_(konosuba)"],
        "iris": ["iris", "iris_stylish_sword", "iris_(konosuba)"],
        "komekko": ["komekko", "komekko_(konosuba)", "megumin_sister"],
        "cecily": ["cecily", "cecily_(konosuba)", "axis_cult_cecily"],
        "arue": ["arue", "arue_(konosuba)"],
        "claire": ["claire", "claire_(konosuba)"],
        "sylvia": ["sylvia", "sylvia_(konosuba)"],
        "lean": ["lean", "lean_(konosuba)"],
        "verdia": ["verdia", "verdia_(konosuba)"],
        "hans": ["hans", "hans_(konosuba)"],
        "yuiyui": ["yuiyui", "crimson_demon_yuiyui", "yuiyui_(konosuba)"]
    },

    "lycoris_recoil": {
        "chisato_nishikigi": ["chisato nishikigi", "chisato_nishikigi", "chisato", "nishikigi"],
        "takina_inoue": ["takina inoue", "takina_inoue", "takina"],
        "mizuki_nakahara": ["mizuki nakahara", "mizuki_nakahara", "mizuki"],
        "kurumi_shinonome": ["kurumi shinonome", "kurumi_shinonome", "walnut", "kurumi"],
        "erika_karuizawa": ["erika karuizawa", "erika_karuizawa", "erika"],
        "sakura_otome": ["sakura otome", "sakura_otome", "sakura"],
        "fuki_himegama": ["fuki himegama", "fuki_himegama", "himegama"],
        "mika": ["mika"],
        "robota": ["robota"],
        "lucy": ["lucy"]
    }
}

CHARACTER_DESCRIPTIONS = {
    "one_piece": {
        "monkey_d_luffy": ("Monkey D. Luffy", "Captain of the Straw Hat Pirates"),
        "roronoa_zoro": ("Roronoa Zoro", "First Mate and Swordsman of the Straw Hat Pirates"),
        "nami": ("Nami", "The Cat Burglar and Navigator of the Straw Hat Pirates"),
        "vinsmoke_sanji": ("Vinsmoke Sanji", "Cook of the Straw Hat Pirates"),
        "nico_robin": ("Nico Robin", "The Devil Child and Archaeologist of the Straw Hat Pirates"),
        "uta": ("Uta", "The Divine Diva and Shanks' Foster Daughter"),
        "rebecca": ("Rebecca", "The Undefeated Gladiator and Princess of Dressrosa"),
        "carrot": ("Carrot", "The Moon Lion Warrior of the Mink Tribe"),
        "jewelry_bonney": ("Jewelry Bonney", "The Big Eater and Captain of the Bonney Pirates"),
        "baby_5": ("Baby 5", "The Living Weapon and Former Donquixote Pirate"),
        "boa_hancock": ("Boa Hancock", "The Pirate Empress and Captain of the Kuja Pirates"),
        "nefertari_vivi": ("Nefertari Vivi", "Princess of Alabasta and Former Straw Hat Companion"),
        "vinsmoke_reiju": ("Vinsmoke Reiju", "The Poison Pink Princess of the Germa 66"),
        "charlotte_linlin": ("Charlotte Linlin", "Big Mom, Captain of the Big Mom Pirates"),
        "shimotsuki_kuina": ("Shimotsuki Kuina", "The Legendary Swordswoman and Zoro's Childhood Friend"),
        "charlotte_smoothie": ("Charlotte Smoothie", "Sweet Commander of the Big Mom Pirates"),
        "shirahoshi": ("Shirahoshi", "The Ancient Weapon Poseidon and Mermaid Princess"),
        "kouzuki_hiyori": ("Kouzuki Hiyori", "Daughter of the Daimyo and Heir to Wano"),
        "catarina_devon": ("Catarina Devon", "The Crescent Moon Hunter of the Blackbeard Pirates"),
        "perona": ("Perona", "The Ghost Princess and Former Member of Thriller Bark"),
        "charlotte_flampe": ("Charlotte Flampe", "Leader of the Special Forces and Charlotte Family Member"),
        "kouzuki_toki": ("Kouzuki Toki", "The Time Traveler and Wife of Oden"),
        "alvida": ("Alvida", "Iron Mace Alvida and Former Captain"),
        "kikunojo": ("Kikunojo", "The Lingering Snow of the Nine Red Scabbards"),
        "vegapunk_lilith": ("Vegapunk Lilith", "Evil Satellite of Dr. Vegapunk"),
        "kaya": ("Kaya", "The Kind-Hearted Heiress of Syrup Village"),
        "monet": ("Monet", "The Snow Woman and Caesar's Secretary"),
        "wanda": ("Wanda", "Warrior of the Mink Tribe"),
        "nico_olvia": ("Nico Olvia", "The Revolutionary Scholar and Robin's Mother"),
        "nojiko": ("Nojiko", "Nami's Adoptive Sister and Bell-mère's Daughter"),
        "charlotte_pudding": ("Charlotte Pudding", "The 35th Daughter of the Charlotte Family"),
        "vegapunk_atlas": ("Vegapunk Atlas", "Combat Satellite of Dr. Vegapunk"),
        "vegapunk_york": ("Vegapunk York", "Analysis Satellite of Dr. Vegapunk"),
        "stussy": ("Stussy", "The Queen of the Pleasure District and CP0 Agent"),
        "tashigi": ("Tashigi", "Marine Captain and Swordswoman"),
        "hina": ("Hina", "The Black Cage Marine Officer"),
        "isuka": ("Isuka", "The Nailing Marine and Former Instructor")
    },

    "naruto": {
        "tsunade_senju": ("Tsunade Senju", "The Fifth Hokage and Legendary Sannin"),
        "sakura_haruno": ("Sakura Haruno", "The Strongest Medical Ninja and Student of Tsunade"),
        "hinata_hyuga": ("Hinata Hyuga", "The Byakugan Princess and Wife of Naruto"),
        "tenten": ("Tenten", "The Weapons Mistress of Team Guy"),
        "temari": ("Temari", "The Wind Mistress and Ambassador of Sunagakure"),
        "kushina_uzumaki": ("Kushina Uzumaki", "The Red Hot-Blooded Habanero and Naruto's Mother"),
        "sarada_uchiha": ("Sarada Uchiha", "Daughter of Sasuke and Future Hokage Aspirant"),
        "himawari_uzumaki": ("Himawari Uzumaki", "Daughter of Naruto with the Byakugan"),
        "ino_yamanaka": ("Ino Yamanaka", "Leader of the Sensory Division and Medical Ninja"),
        "kurenai_yuhi": ("Kurenai Yuhi", "The Genjutsu Mistress and Team 8 Leader"),
        "anko_mitarashi": ("Anko Mitarashi", "The Snake Mistress and Former Student of Orochimaru"),
        "shizune": ("Shizune", "First Apprentice of Tsunade and Chief Medical Ninja"),
        "karin_uzumaki": ("Karin Uzumaki", "The Sensory Ninja and Former Member of Taka"),
        "konan": ("Konan", "The Angel of Amegakure and Member of the Akatsuki"),
        "mei_terumi": ("Mei Terumi", "The Fifth Mizukage with Dual Kekkei Genkai"),
        "samui": ("Samui", "The Cool-Headed Kunoichi of Kumogakure"),
        "karui": ("Karui", "The Fierce Warrior of Kumogakure"),
        "mabui": ("Mabui", "The Raikage's Assistant and Transport Specialist"),
        "yugao_uzuki": ("Yugao Uzuki", "ANBU Captain and Master Swordswoman"),
        "tsume_inuzuka": ("Tsume Inuzuka", "Matriarch of the Inuzuka Clan"),
        "hana_inuzuka": ("Hana Inuzuka", "The Veterinary Ninja and Sister of Kiba"),
        "natsu_hyuga": ("Natsu Hyuga", "Caretaker of the Hyuga Clan"),
        "yakumo_kurama": ("Yakumo Kurama", "Heiress of the Kurama Clan"),
        "tsunami": ("Tsunami", "Kind-Hearted Civilian of the Land of Waves"),
        "ayame": ("Ayame", "Daughter of Teuchi and Ramen Chef"),
        "yugito_nii": ("Yugito Nii", "The Two-Tails Jinchūriki of Kumogakure"),
        "fuu": ("Fuu", "The Seven-Tails Jinchūriki of Takigakure"),
        "hokuto": ("Hokuto", "Star Village Kunoichi"),
        "hanabi_hyuga": ("Hanabi Hyuga", "Leader of the Hyuga Clan"),
        "moegi": ("Moegi", "Member of Team Ebisu and Wood Release User"),
        "sumire_kakei": ("Sumire Kakei", "Class Rep and Former Root Member"),
        "chocho_akimichi": ("Chocho Akimichi", "The Butterfly Ninja of the New Generation"),
        "mirai_sarutobi": ("Mirai Sarutobi", "Daughter of Asuma and Kurenai"),
        "wasabi_izuno": ("Wasabi Izuno", "Cat-Like Ninja of the New Generation"),
        "namida_suzumeno": ("Namida Suzumeno", "Sound-Based Ninja of the New Generation")
    },

    "fairy_tail": {
        "lucy_heartfilia": ("Lucy Heartfilia", "Celestial Spirit Mage and Novel Writer"),
        "erza_scarlet": ("Erza Scarlet", "Titania, Queen of the Fairies and S-Class Requip Mage"),
        "wendy_marvell": ("Wendy Marvell", "The Sky Dragon Slayer and Healing Specialist"),
        "juvia_lockser": ("Juvia Lockser", "The Rain Woman and Water Magic Master"),
        "levy_mcgarden": ("Levy McGarden", "Solid Script Mage and Leader of Shadow Gear"),
        "mirajane_strauss": ("Mirajane Strauss", "The Demon Take-Over Mage and Former S-Class"),
        "lisanna_strauss": ("Lisanna Strauss", "Animal Soul Take-Over Mage and Mirajane's Sister"),
        "cana_alberona": ("Cana Alberona", "Card Magic Expert and Gildarts' Daughter"),
        "evergreen": ("Evergreen", "The Fairy Queen of the Thunder Legion"),
        "bisca_connell": ("Bisca Connell", "The Gunslinger Mage and Alzack's Wife"),
        "laki_olietta": ("Laki Olietta", "Wood-Make Magic User"),
        "kinana": ("Kinana", "Former Snake Cubellios and Guild Barmaid"),
        "mavis_vermillion": ("Mavis Vermillion", "First Guild Master and Fairy Tactician"),
        "meredy": ("Meredy", "Sensory Link Mage of Crime Sorcière"),
        "ultear_milkovich": ("Ultear Milkovich", "Arc of Time Master and Founder of Crime Sorcière"),
        "yukino_agria": ("Yukino Agria", "Celestial Spirit Mage of Sabertooth"),
        "minerva_orlando": ("Minerva Orlando", "Territory Magic User and Lady of Sabertooth"),
        "kagura_mikazuchi": ("Kagura Mikazuchi", "Gravity Magic Swordswoman of Mermaid Heel"),
        "milliana": ("Milliana", "Cat-Like Binding Magic User of Mermaid Heel"),
        "flare_corona": ("Flare Corona", "Crimson Hair Mage of Raven Tail"),
        "jenny_realight": ("Jenny Realight", "Take-Over Mage and Blue Pegasus Model"),
        "sherry_blendy": ("Sherry Blendy", "Doll Attack Mage and Ren's Wife"),
        "chelia_blendy": ("Chelia Blendy", "Former Sky God Slayer and Wendy's Friend"),
        "sorano_agria": ("Sorano Agria", "Angel of the Oracion Seis and Yukino's Sister"),
        "brandish_mu": ("Brandish μ", "Mass Manipulation Mage of the Spriggan 12"),
        "dimaria_yesta": ("Dimaria Yesta", "Time God of the Spriggan 12"),
        "irene_belserion": ("Irene Belserion", "Scarlet Despair and Mother of Dragon Slaying Magic"),
        "hisui_fiore": ("Hisui E. Fiore", "Princess of Fiore and Jade Dragon")
    },

    "dragon_ball": {
        "bulma_briefs": ("Bulma Briefs", "Scientific Genius and Founder of Capsule Corporation"),
        "chi_chi": ("Chi-Chi", "The Ox Princess and Wife of Goku"),
        "videl_satan": ("Videl Satan", "Crime Fighter and Wife of Gohan"),
        "pan": ("Pan", "Quarter-Saiyan Daughter of Gohan and Videl"),
        "android_18": ("Android 18", "Former Enemy turned Z-Fighter and Krillin's Wife"),
        "bulla_briefs": ("Bulla Briefs", "Half-Saiyan Daughter of Vegeta and Bulma"),
        "launch": ("Launch", "Jekyll and Hyde Personality Fighter"),
        "marron": ("Marron", "Daughter of Krillin and Android 18"),
        "mai": ("Mai", "Former Enemy turned Time Patrol Member"),
        "ranfan": ("Ranfan", "World Tournament Fighter"),
        "vados": ("Vados", "Angel Attendant of Universe 6"),
        "caulifla": ("Caulifla", "Universe 6 Saiyan Prodigy"),
        "kale": ("Kale", "Legendary Super Saiyan of Universe 6"),
        "ribrianne": ("Ribrianne", "Love Warrior of Universe 2"),
        "oceanus_shenron": ("Oceanus Shenron", "Shadow Dragon of Water and Wind"),
        "gine": ("Gine", "Mother of Goku and Former Saiyan Warrior"),
        "fasha": ("Fasha", "Member of Bardock's Elite Squad"),
        "zangya": ("Zangya", "Warrior of the Galaxy Soldiers"),
        "towa": ("Towa", "Dark Scientist of the Demon Realm"),
        "chronoa": ("Chronoa", "Supreme Kai of Time"),
        "arale_norimaki": ("Arale Norimaki", "Android Girl with Superhuman Strength")
    },

    "attack_on_titan": {
        "mikasa_ackerman": ("Mikasa Ackerman", "The Last Asian and Elite Survey Corps Soldier"),
        "annie_leonhart": ("Annie Leonhart", "The Female Titan and Former Military Police"),
        "historia_reiss": ("Historia Reiss", "The True Queen of the Walls"),
        "sasha_braus": ("Sasha Braus", "The Potato Girl and Expert Marksman"),
        "hange_zoe": ("Hange Zoë", "14th Commander of the Survey Corps and Titan Researcher"),
        "ymir": ("Ymir", "The Jaw Titan and Historia's Protector"),
        "pieck_finger": ("Pieck Finger", "The Cart Titan and Marley's Strategist"),
        "gabi_braun": ("Gabi Braun", "Warrior Candidate and Reiner's Cousin"),
        "frieda_reiss": ("Frieda Reiss", "Former Holder of the Founding Titan"),
        "carla_yeager": ("Carla Yeager", "Eren's Mother and Victim of the Fall"),
        "dina_fritz": ("Dina Fritz", "The Smiling Titan and Grisha's First Wife"),
        "petra_ral": ("Petra Ral", "Elite Member of the Levi Squad"),
        "rico_brzenska": ("Rico Brzenska", "Elite Garrison Squad Leader"),
        "yelena": ("Yelena", "Zeke's Devoted Follower and Anti-Marleyan"),
        "kiyomi_azumabito": ("Kiyomi Azumabito", "Ambassador of Hizuru"),
        "louise": ("Louise", "Young Soldier Inspired by Mikasa"),
        "nifa": ("Nifa", "Member of Squad Hange"),
        "lynne": ("Lynne", "Veteran Survey Corps Member"),
        "ilse_langnar": ("Ilse Langnar", "Survey Corps Researcher"),
        "nanaba": ("Nanaba", "Veteran Survey Corps Member and Squad Leader")
    },

    "demon_slayer": {
        "nezuko_kamado": ("Nezuko Kamado", "Demon Sister of Tanjiro with Unique Blood Art"),
        "kanao_tsuyuri": ("Kanao Tsuyuri", "Flower Breathing User and Shinobu's Protégé"),
        "shinobu_kocho": ("Shinobu Kocho", "Insect Hashira and Master of Poison"),
        "kanae_kocho": ("Kanae Kocho", "Former Flower Hashira and Shinobu's Sister"),
        "mitsuri_kanroji": ("Mitsuri Kanroji", "Love Hashira with Unique Muscle Composition"),
        "daki": ("Daki", "Upper Rank Six Demon and Oiran"),
        "tamayo": ("Tamayo", "Doctor Demon Who Defied Muzan"),
        "makio": ("Makio", "Uzui's Wife and Kunoichi"),
        "suma": ("Suma", "Uzui's Wife and Shinobi"),
        "hinatsuru": ("Hinatsuru", "Uzui's Wife and Ninja"),
        "aoi_kanzaki": ("Aoi Kanzaki", "Medical Support at the Butterfly Estate"),
        "kiyo_terauchi": ("Kiyo Terauchi", "Butterfly Estate Medical Staff"),
        "sumi_nakahara": ("Sumi Nakahara", "Butterfly Estate Medical Staff"),
        "naho_takada": ("Naho Takada", "Butterfly Estate Medical Staff"),
        "goto": ("Goto", "Kakushi Corps Leader"),
        "amane": ("Amane", "Ubuyashiki Household Staff"),
        "mukago": ("Mukago", "Spider Demon of Mt. Natagumo"),
        "ruka": ("Ruka", "Spider Demon Family Member"),
        "hinaki_ubuyashiki": ("Hinaki Ubuyashiki", "Daughter of Kagaya Ubuyashiki"),
        "nichika_ubuyashiki": ("Nichika Ubuyashiki", "Daughter of the Demon Slayer Leader"),
        "kuina_ubuyashiki": ("Kuina Ubuyashiki", "Youngest Daughter of Master Ubuyashiki")
    },

    "jujutsu_kaisen": {
        "nobara_kugisaki": ("Nobara Kugisaki", "First-Year Sorcerer and Master of Straw Doll Technique"),
        "maki_zenin": ("Maki Zenin", "Cursed Tools Expert and Former Zenin Clan Member"),
        "mei_mei": ("Mei Mei", "Grade 1 Sorcerer and Money-Motivated Bird Strike User"),
        "kasumi_miwa": ("Kasumi Miwa", "Kyoto Student and New Shadow Style Swordsman"),
        "momo_nishimiya": ("Momo Nishimiya", "Broom-Flying Kyoto Second-Year"),
        "mai_zenin": ("Mai Zenin", "Maki's Twin with Construction Technique"),
        "yuki_tsukumo": ("Yuki Tsukumo", "Special Grade Sorcerer and Researcher"),
        "rika_orimoto": ("Rika Orimoto", "Yuta's Cursed Spirit Companion"),
        "utahime_iori": ("Utahime Iori", "Kyoto Teacher and Barrier Technique User"),
        "tsumiki_fushiguro": ("Tsumiki Fushiguro", "Megumi's Cursed Sister"),
        "manami_suda": ("Manami Suda", "Curse Victim and Mahito's Target"),
        "saori_rokujo": ("Saori Rokujo", "Nobara's Middle School Friend"),
        "shoko_ieiri": ("Shoko Ieiri", "Jujutsu Tech's Doctor and Reverse Cursed Technique User"),
        "mimiko_hasaba": ("Mimiko Hasaba", "Twin Curse User"),
        "nanako_hasaba": ("Nanako Hasaba", "Twin Curse User")
    },

    "cowboy_bebop": {
         "faye_valentine": ("Faye Valentine", "Amnesiac Bounty Hunter with a Massive Debt"),
        "edward_wong": ("Edward Wong", "Eccentric Hacker Prodigy"),
        "julia": ("Julia", "Mysterious Woman from Spike's Past"),
        "meifa_puzi": ("Meifa Puzi", "Feng Shui Master's Daughter"),
        "judy": ("Judy", "Television Show Host"),
        "anastasia": ("Anastasia", "Bar Owner and Spike's Friend"),
        "alisa": ("Alisa", "Jet's Former Love Interest"),
        "victoria_terraforming": ("V.T.", "Space Trucker and Racing Queen"),
        "stella_bonnaro": ("Stella Bonnaro", "Saxophone Player's Daughter"),
        "coffee": ("Coffee", "Owner of the Mexican Restaurant"),
        "katrina_solensan": ("Katrina Solensan", "Assassin turned Environmental Activist")
    },

    "spy_x_family": {
        "yor_forger": ("Yor Forger", "The Thorn Princess and Secret Assassin"),
        "anya_forger": ("Anya Forger", "Telepathic Child Spy-in-Training"),
        "sylvia_sherwood": ("Sylvia Sherwood", "Handler of WISE and Operation Strix Manager"),
        "fiona_frost": ("Fiona Frost", "Elite WISE Agent and Twilight's Former Partner"),
        "becky_blackbell": ("Becky Blackbell", "Anya's Best Friend and Rich Heiress"),
        "sharon": ("Sharon", "Kind Shop Owner and Information Broker"),
        "melinda_desmond": ("Melinda Desmond", "Donovan Desmond's Reserved Wife"),
        "camilla": ("Camilla", "Sharon's Sister and Shop Assistant"),
        "karen_gloomy": ("Karen Gloomy", "Photography Club Member"),
        "dominic": ("Dominic", "Garden's Handler"),
        "martha": ("Martha", "The Forger Family's Landlady")
    },

    "one_punch_man": {
        "fubuki": ("Fubuki", "The Hellish Blizzard and B-Class Hero"),
        "tatsumaki": ("Tatsumaki", "The Terrible Tornado and S-Class Hero"),
        "psykos": ("Psykos", "Leader of the Monster Association"),
        "suiko": ("Suiko", "Suiryu's Sister and Martial Artist"),
        "lin_lin": ("Lin Lin", "A-Class Hero and Super Fight Participant"),
        "lily": ("Lily", "The Three-Section Staff and Fubuki Group Member"),
        "do_s": ("Do-S", "The Monster Princess and Dominatrix"),
        "mosquito_girl": ("Mosquito Girl", "Blood-Drinking Monster"),
        "captain_mizuki": ("Captain Mizuki", "Track and Field Hero"),
        "shadow_ring": ("Shadow Ring", "A-Class Ninja Hero"),
        "zenko": ("Zenko", "Metal Bat's Little Sister"),
        "madame_shibabawa": ("Madame Shibabawa", "The Great Fortune Teller"),
        "goddess_glasses": ("Goddess Glasses", "Support Hero"),
        "swim": ("Swim", "Tank Top Hero Group Member"),
        "pai": ("Pai", "Tank Top Hero Group Member")
    },

    "league_of_legends": {
        "ahri": ("Ahri", "The Nine-Tailed Fox and Vastayan Charmer"),
        "luxanna_crownguard": ("Luxanna Crownguard", "The Lady of Luminosity"),
        "jinx": ("Jinx", "The Loose Cannon of Zaun"),
        "vi": ("Vi", "The Piltover Enforcer"),
        "caitlyn": ("Caitlyn", "The Sheriff of Piltover"),
        "leona": ("Leona", "The Radiant Dawn of Mount Targon"),
        "diana": ("Diana", "The Scorn of the Moon"),
        "ashe": ("Ashe", "The Frost Archer and Queen of Freljord"),
        "katarina": ("Katarina", "The Sinister Blade of Noxus"),
        "sarah_fortune": ("Sarah Fortune", "The Bounty Hunter of Bilgewater"),
        "akali": ("Akali", "The Rogue Assassin"),
        "anivia": ("Anivia", "The Cryophoenix"),
        "annie": ("Annie", "The Dark Child"),
        "bel_veth": ("Bel'Veth", "The Empress of the Void"),
        "briar": ("Briar", "The Hungry Hydra"),
        "cassiopeia": ("Cassiopeia", "The Serpent's Embrace"),
        "elise": ("Elise", "The Spider Queen"),
        "evelynn": ("Evelynn", "Agony's Embrace"),
        "fiora": ("Fiora", "The Grand Duelist"),
        "gwen": ("Gwen", "The Hallowed Seamstress"),
        "illaoi": ("Illaoi", "The Kraken Priestess"),
        "irelia": ("Irelia", "The Blade Dancer"),
        "janna": ("Janna", "The Storm's Fury"),
        "kaisa": ("Kai'Sa", "Daughter of the Void"),
        "kalista": ("Kalista", "The Spear of Vengeance"),
        "karma": ("Karma", "The Enlightened One"),
        "kindred": ("Kindred", "The Eternal Hunters"),
        "leblanc": ("LeBlanc", "The Deceiver"),
        "lillia": ("Lillia", "The Bashful Bloom"),
        "lissandra": ("Lissandra", "The Ice Witch"),
        "morgana": ("Morgana", "The Fallen"),
        "nami": ("Nami", "The Tidecaller"),
        "neeko": ("Neeko", "The Curious Chameleon"),
        "nidalee": ("Nidalee", "The Bestial Huntress"),
        "nilah": ("Nilah", "The Joy Unbound"),
        "orianna": ("Orianna", "The Lady of Clockwork"),
        "poppy": ("Poppy", "Keeper of the Hammer"),
        "qiyana": ("Qiyana", "Empress of the Elements"),
        "rell": ("Rell", "The Iron Maiden"),
        "riven": ("Riven", "The Exile"),
        "samira": ("Samira", "The Desert Rose"),
        "senna": ("Senna", "The Redeemer"),
        "seraphine": ("Seraphine", "The Starry-Eyed Songstress"),
        "sejuani": ("Sejuani", "Fury of the North"),
        "shyvana": ("Shyvana", "The Half-Dragon"),
        "sivir": ("Sivir", "The Battle Mistress"),
        "sona": ("Sona", "Maven of the Strings"),
        "soraka": ("Soraka", "The Starchild"),
        "syndra": ("Syndra", "The Dark Sovereign"),
        "taliyah": ("Taliyah", "The Stoneweaver"),
        "tristana": ("Tristana", "The Yordle Gunner"),
        "vayne": ("Vayne", "The Night Hunter"),
        "vex": ("Vex", "The Gloomist"),
        "xayah": ("Xayah", "The Rebel"),
        "yuumi": ("Yuumi", "The Magical Cat"),
        "zeri": ("Zeri", "The Spark of Zaun"),
        "zoe": ("Zoe", "The Aspect of Twilight"),
        "zyra": ("Zyra", "Rise of the Thorns")
    },

    "hunter_x_hunter": {
        "biscuit_krueger": ("Biscuit Krueger", "Master Nen Teacher and Precious Stone Hunter"),
        "palm_siberia": ("Palm Siberia", "Chimera Ant Soldier and Clairvoyant"),
        "machi": ("Machi", "Spider #3 and Phantom Troupe's Medic"),
        "shizuku": ("Shizuku", "Spider #8 and Vacuum User"),
        "canary": ("Canary", "Zoldyck Family Butler and Killua's Ally"),
        "neferpitou": ("Neferpitou", "Royal Guard and Doctor Blythe User"),
        "komugi": ("Komugi", "Gungi Champion and Meruem's Teacher"),
        "pakunoda": ("Pakunoda", "Spider #9 and Memory Reader"),
        "melody": ("Melody", "Music Hunter with Enhanced Hearing"),
        "zazan": ("Zazan", "Chimera Ant Queen of Meteor City"),
        "eliza": ("Eliza", "Squala's Girlfriend and Victim"),
        "amane": ("Amane", "Zoldyck Butler and Canary's Senior"),
        "tsubone": ("Tsubone", "Zoldyck Head Butler"),
        "kalluto_zoldyck": ("Kalluto Zoldyck", "Youngest Zoldyck and Spider #4"),
        "kikyo_zoldyck": ("Kikyo Zoldyck", "Matriarch of the Zoldyck Family"),
        "alluka_zoldyck": ("Alluka Zoldyck", "Killua's Sister and Wish Granter"),
        "cheadle_yorkshire": ("Cheadle Yorkshire", "Zodiac Dog and Medical Hunter"),
        "menchi": ("Menchi", "Gourmet Hunter and Examiner"),
        "ponzu": ("Ponzu", "Bee User and Hunter Examinee")
    },

    "fullmetal_alchemist": {
         "winry_rockbell": ("Winry Rockbell", "Automail Engineer and Edward's Wife"),
        "riza_hawkeye": ("Riza Hawkeye", "The Hawk's Eye and Mustang's Lieutenant"),
        "olivier_armstrong": ("Olivier Armstrong", "The Northern Wall of Briggs"),
        "izumi_curtis": ("Izumi Curtis", "The Alchemist Teacher"),
        "mei_chang": ("Mei Chang", "Alkahestry Princess of Xing"),
        "maria_ross": ("Maria Ross", "Framed Lieutenant and Loyal Soldier"),
        "gracia_hughes": ("Gracia Hughes", "Maes Hughes' Widow"),
        "elicia_hughes": ("Elicia Hughes", "Maes Hughes' Daughter"),
        "lan_fan": ("Lan Fan", "Ling's Personal Guard and Assassin"),
        "paninya": ("Paninya", "Rush Valley's Automail Thief"),
        "sheska": ("Sheska", "Photographic Memory Librarian"),
        "rose_thomas": ("Rose Thomas", "Reole's Religious Follower"),
        "catherine_armstrong": ("Catherine Elle Armstrong", "Strong Arm's Sister"),
        "martel": ("Martel", "Chimera Soldier of Devil's Nest"),
        "trisha_elric": ("Trisha Elric", "Loving Mother of Edward and Alphonse"),
        "pinako_rockbell": ("Pinako Rockbell", "Legendary Automail Engineer"),
        "lust": ("Lust", "The Ultimate Lance Homunculus"),
        "dante": ("Dante", "Ancient Alchemist and Main Antagonist"),
        "clara": ("Clara", "The Phantom Thief Psiren")
    },

    "my_hero_academia": {
        "ochaco_uraraka": ("Ochaco Uraraka", "Zero Gravity Hero: Uravity"),
        "tsuyu_asui": ("Tsuyu Asui", "Rainy Season Hero: Froppy"),
        "momo_yaoyorozu": ("Momo Yaoyorozu", "Everything Hero: Creati"),
        "kyoka_jirou": ("Kyoka Jirou", "Hearing Hero: Earphone Jack"),
        "toru_hagakure": ("Toru Hagakure", "Stealth Hero: Invisible Girl"),
        "mina_ashido": ("Mina Ashido", "Pinky: The Acid Hero"),
        "yu_takeyama": ("Yu Takeyama", "Giant Hero: Mount Lady"),
        "nemuri_kayama": ("Nemuri Kayama", "R-Rated Hero: Midnight"),
        "rumi_usagiyama": ("Rumi Usagiyama", "Rabbit Hero: Mirko"),
        "ryuko_tatsuma": ("Ryuko Tatsuma", "Dragon Hero: Ryukyu"),
        "nejire_hado": ("Nejire Hado", "Wave Motion Hero: Nejire-chan"),
        "shino_sosaki": ("Shino Sosaki", "Wild Wild Pussycats: Mandalay"),
        "ryuko_tsuchikawa": ("Ryuko Tsuchikawa", "Wild Wild Pussycats: Pixie-Bob"),
        "tomoko_shiretoko": ("Tomoko Shiretoko", "Wild Wild Pussycats: Ragdoll"),
        "itsuka_kendo": ("Itsuka Kendo", "Battle Fist of Class 1-B"),
        "pony_tsunotori": ("Pony Tsunotori", "Class 1-B's Exchange Student"),
        "kinoko_komori": ("Kinoko Komori", "Mushroom Girl of Class 1-B"),
        "yui_kodai": ("Yui Kodai", "Size Master of Class 1-B"),
        "reiko_yanagi": ("Reiko Yanagi", "Poltergeist of Class 1-B"),
        "setsuna_tokage": ("Setsuna Tokage", "Lizard Hero: Lizardy"),
        "melissa_shield": ("Melissa Shield", "Support Item Developer"),
        "inko_midoriya": ("Inko Midoriya", "Deku's Caring Mother"),
        "fuyumi_todoroki": ("Fuyumi Todoroki", "Shoto's Supportive Sister"),
        "eri": ("Eri", "The Girl with Rewind Powers"),
        "nana_shimura": ("Nana Shimura", "All Might's Mentor"),
        "himiko_toga": ("Himiko Toga", "League of Villains' Transform Expert")
    },

    "jojos_bizarre_adventure": {
        "jolyne_cujoh": ("Jolyne Cujoh", "Stone Free Stand User and Jotaro's Daughter"),
        "lisa_lisa": ("Lisa Lisa", "Hamon Master and Joseph's Mother"),
        "erina_pendleton": ("Erina Pendleton", "Jonathan's Wife and Hamon Healer"),
        "trish_una": ("Trish Una", "Spice Girl Stand User and Diavolo's Daughter"),
        "suzi_q": ("Suzi Q", "Joseph's Wife and Holy's Mother"),
        "holly_kujo": ("Holly Kujo", "Stand-Afflicted Mother of Jotaro"),
        "yukako_yamagishi": ("Yukako Yamagishi", "Love Deluxe Stand User and Koichi's Girlfriend"),
        "reimi_sugimoto": ("Reimi Sugimoto", "Ghost Girl and Kira's First Victim"),
        "hot_pants": ("Hot Pants", "Cream Starter Stand User and Nun"),
        "lucy_steel": ("Lucy Steel", "Key Ally in Steel Ball Run"),
        "yasuho_hirose": ("Yasuho Hirose", "Paisley Park Stand User and Josuke's Aid"),
        "hermes_costello": ("Hermes Costello", "Kiss Stand User and Jolyne's Friend"),
        "foo_fighters": ("Foo Fighters", "Plankton Stand User Known as F.F."),
        "ermes_costello": ("Ermes Costello", "Vengeful Sister with Kiss Stand"),
        "gwess": ("Gwess", "Goo Goo Dolls Stand User"),
        "mariah": ("Mariah", "Bastet Stand User and DIO's Minion"),
        "midler": ("Midler", "High Priestess Stand User"),
        "anne": ("Anne", "Stowaway Girl from Part 3"),
        "tomoko_higashikata": ("Tomoko Higashikata", "Josuke's Mother and Joseph's Former Lover")
    },

    "pokemon": {
        "misty_waterflower": ("Misty Waterflower", "Cerulean City Gym Leader and Water Pokemon Master"),
        "may_maple": ("May Maple", "Hoenn Coordinator and Daughter of Norman"),
        "dawn_berlitz": ("Dawn Berlitz", "Sinnoh Coordinator and Piplup's Trainer"),
        "serena": ("Serena", "Kalos Performer and Ash's Childhood Friend"),
        "iris": ("Iris", "Dragon Master and Unova Champion"),
        "lillie": ("Lillie", "Ultra Beast Researcher and Aether Foundation Heir"),
        "cynthia": ("Cynthia", "Sinnoh Champion and Archaeological Expert"),
        "diantha": ("Diantha", "Kalos Champion and Movie Star"),
        "lusamine": ("Lusamine", "Aether Foundation President"),
        "sabrina": ("Sabrina", "Saffron City Gym Leader and Psychic Master"),
        "erika": ("Erika", "Celadon City Gym Leader and Grass Expert"),
        "whitney": ("Whitney", "Goldenrod City Gym Leader with Miltank"),
        "jasmine": ("Jasmine", "Olivine City Gym Leader and Steel Specialist"),
        "clair": ("Clair", "Blackthorn City Gym Leader and Dragon Tamer"),
        "flannery": ("Flannery", "Lavaridge Town Gym Leader and Fire Expert"),
        "winona": ("Winona", "Fortree City Gym Leader and Flying Specialist"),
        "roxanne": ("Roxanne", "Rustboro City Gym Leader and Rock Expert"),
        "gardenia": ("Gardenia", "Eterna City Gym Leader and Grass Master"),
        "candice": ("Candice", "Snowpoint City Gym Leader and Ice Expert"),
        "fantina": ("Fantina", "Hearthome City Gym Leader and Ghost Specialist"),
        "elesa": ("Elesa", "Nimbasa City Gym Leader and Model"),
        "skyla": ("Skyla", "Mistralton City Gym Leader and Pilot"),
        "korrina": ("Korrina", "Shalour City Gym Leader and Mega Evolution User"),
        "valerie": ("Valerie", "Laverre City Gym Leader and Fairy Expert"),
        "olympia": ("Olympia", "Anistar City Gym Leader and Psychic Master"),
        "mallow": ("Mallow", "Alola Trial Captain and Chef"),
        "lana": ("Lana", "Alola Trial Captain and Fisher"),
        "nessa": ("Nessa", "Hulbury Gym Leader and Model"),
        "marnie": ("Marnie", "Spikemuth Gym Leader and Rival"),
        "sonia": ("Sonia", "Pokemon Professor and Researcher"),
        "professor_juniper": ("Professor Juniper", "Unova's Regional Professor"),
        "nurse_joy": ("Nurse Joy", "Pokemon Center Healer"),
        "officer_jenny": ("Officer Jenny", "Pokemon Police Officer"),
        "jessie": ("Jessie", "Team Rocket Member and Former Coordinator"),
        "bonnie": ("Bonnie", "Clemont's Sister and Future Trainer"),
        "rosa": ("Rosa", "Unova Pokemon Trainer")
    },

    "hatsune_miku": {
        "hatsune_miku": ("Hatsune Miku", "The World's Virtual Idol and First Crypton Vocaloid"),
        "meiko": ("MEIKO", "The First Japanese Commercial Vocaloid"),
        "kagamine_rin": ("Kagamine Rin", "The Energetic Half of the Kagamine Mirror Images"),
        "megurine_luka": ("Megurine Luka", "The Bilingual Diva of the Vocaloid World"),
        "megpoid_gumi": ("GUMI", "The Green-Haired Voice of Internet Co.'s Megpoid"),
        "kasane_teto": ("Kasane Teto", "The Popular UTAU Voice Bank and Unofficial Vocaloid"),
        "akita_neru": ("Akita Neru", "The Tsundere Derivative Character with a Cell Phone"),
        "yowane_haku": ("Yowane Haku", "The Failed Singing Voice Derivative Character"),
        "otomachi_una": ("Otomachi Una", "The Sugar Voice Internet Co. Vocaloid"),
        "ia": ("IA", "The Spiritual Voiced 1st ARIA Vocaloid"),
        "cul": ("CUL", "The Red-Haired Rock-Style Vocaloid"),
        "lily": ("Lily", "The Internet Co. Ltd. Rock-inspired Vocaloid"),
        "sf_a2_miki": ("SF-A2 Miki", "The AH-Software Cherry-Voiced Vocaloid"),
        "yuzuki_yukari": ("Yuzuki Yukari", "The Purple-Haired Voiceroid and Vocaloid")
    },

    "konosuba": {
        "aqua": ("Aqua", "The Useless Goddess of Water"),
        "megumin": ("Megumin", "Arch Wizard of the Crimson Demon Clan"),
        "lalatina_dustiness": ("Lalatina Dustiness Ford", "Crusader Known as Darkness"),
        "wiz": ("Wiz", "Former Demon King General turned Shop Owner"),
        "yunyun": ("Yunyun", "Chief of the Crimson Demon Clan"),
        "chris": ("Chris", "Thief and Secret Goddess Eris"),
        "luna": ("Luna", "Guild Receptionist"),
        "sena": ("Sena", "Prosecuting Knight"),
        "wolbach": ("Wolbach", "Goddess of Sloth and Violence"),
        "iris": ("Iris", "Princess of the Kingdom"),
        "komekko": ("Komekko", "Megumin's Little Sister"),
        "cecily": ("Cecily", "Axis Cult Priest"),
        "arue": ("Arue", "Crimson Demon Novelist"),
        "claire": ("Claire", "Royal Guard Captain"),
        "sylvia": ("Sylvia", "Chimera"),
        "lean": ("Lean", "Royal Guard"),
        "verdia": ("Verdia", "Dullahan General"),
        "hans": ("Hans", "Deadly Poison Slime"),
        "yuiyui": ("Yuiyui", "Megumin's Mother")
    },

    "lycoris_recoil": {
        "chisato_nishikigi": ("Chisato Nishikigi", "Lycoris Operative with Artificial Heart"),
        "takina_inoue": ("Takina Inoue", "Former DA Agent and Chisato's Partner"),
        "mizuki_nakahara": ("Mizuki Nakahara", "Cafe LycoReco Staff Member"),
        "kurumi_shinonome": ("Kurumi Shinonome", "Hacker Known as Walnut"),
        "erika_karuizawa": ("Erika Karuizawa", "Lycoris Commander"),
        "sakura_otome": ("Sakura Otome", "Skilled Lycoris Operative"),
        "fuki_himegama": ("Fuki Himegama", "Strict Lycoris Squad Leader"),
        "mika": ("Mika", "Cafe LycoReco Owner"),
        "robota": ("Robota", "Cafe LycoReco Regular Customer"),
        "lucy": ("Lucy", "International Arms Dealer")
    }
}

VALID_SERIES = set(CHARACTER_MAPPINGS.keys())

def get_series_display_name(series_key: str) -> str:
    """Convert series key to display name"""
    return series_key.replace('_', ' ').title()

def get_character_display_name(char_key: str) -> str:
    """Convert character key to display name"""
    return char_key.replace('_', ' ').title()